### ISSUE TITLE
The format of sqlmap

### ISSUE THREAD

**Issue by lijiecong** [taobao/sqlautoreview#1]
There are two elements in the sqlmap.xml, but I didn't now what the format of D:\danchen\sql\test.xm. I'm new in database, so could you upload the test.xml to the github. Otherwise I didn't know what the format of sql map file. thanks
<sqlmapfile>
    <file_id>100</file_id>
    <file_name>D:\danchen\sql\test.xml</file_name>
</sqlmapfile>

**Comment by taobao-zhaolin** [comment]
我上传了一个示例
https://github.com/taobao-zhaolin/sqlautoreview/blob/master/test.xml

**Comment by lijiecong** [comment]
Thanks!
